### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by JerryBocciJr** [sheley1998/EventLoop#2]
Sheley1998,
I am having some compatibility issues using this code with the Ractiv Touch+ source code.  Would you please take a look and give me an update?  See https://github.com/Ractiv/touch_plus_source_code

**Comment by nm17** [comment]
@JerryBocciJr What kind of compatibility issues are you having?

**Comment by touchhope** [comment]
@NeverMine17

Hi Danil,

Jerry is joking.

I think sarcastic issue posts are his only way to let know to Lai that, as 2058 others backers and without counting also numerous buyers (I'm one of these idiots who bought a $60 unit : see out community on http://gharbi.me/ractiv/), he still don't digest the broken Kickstarter project Haptix (https://www.kickstarter.com/projects/haptix/haptix-multitouch-reinvented/comments) which became Ractiv's Touchplus device (http://www.ractiv.com/blog/setting-up-touch/).

I personnally got in touch with several coding experts (Umar Nizamani: https://github.com/umarniz/TouchPlusLib , Matthew Fogle: https://github.com/shadowmite/TouchPlusCMDR , Andrea Tagliasacchi: https://github.com/OpenGP/htrack/ and even with TUIO cursor (used in Lai's code) creator Martin Kaltenbrunner: https://github.com/mkalten/TUIO11_NET)

Backer Robert Sweetman from UK even had proposed to freely send his unit, but all these people smartly made their own conclusion which is all this doesn't worth (because of the badly usb interfaced device unable to give access to internal calculation capatibilities of Etron's eSP870 chipset : so too much latency means poor performance, or maybe some kind of pyramidal optimized algorithm could do thr trick ?).

However, this virtual trackpad on the keyboard from a stereo camera, clipped on the top of the screen, did worked on 0.55b beta version as seen on youtube (https://www.youtube.com/watch?v=ulFTmjiwmAA). So Alexandru Bauer and also Lachlan Pollock had experimented working software on this device but sadly didn't keep any copy.

The source code allow you to compile something that never launch the famous white and green circles driven through csharp process (win_cursor_plus).

As I'm far from being a coding expert, I had desperately tried to switch some parameters, especially on commit number d679834 on 24 Jul 2015 https://github.com/Ractiv/touch_plus_source_code/commit/d6798349bd6b4d385c4bef170a068a914b99287f

Indeed, in this earlier commit, the four processes (deamon_plus, track_plus, menu_plus and win_cursor_plus) are launched at least (which isn't always the case in others commits) but only in console mode and I don't see where we can specify the running mode (launching csharp process from c++ process).

Maybe a true or false (or 1 or 0) somewhere in the code but where exactly ? In later commits, you get "assertion failed" error message : is this csharp app (win_cursor_plus) trying to badly dialog with windows interface ? 

Very last commits give you instead a blue error message from windows 10 which tell you "this app can't be launched on this version" at the time win_cursor_plus is about to run.

4 keys calibration system on keyboard surface is finally abandoned in the later commits with a new calibrating circular jauge and we wonder how calibration is made to get coordonates of touchable area ?

Would you like to freely receive a unit to have fun with this little device and maybe try to give us some help to get a minimal virtual surface pointing system ?

Thanks in advance and nevermind if you don't have time to loss on this dead project.

Best regards,

Christian (or Touchhope on http://gharbi.me/ractiv/ )

**Comment by sheley1998** [comment]
This is getting seriously creepy. How did you get his name? I'm closing your issues/blocking you guys.
